import Sidebar from '@/components/Sidebar';
import SidebarFull from '@/components/SidebarFull';
import 'line-awesome/dist/line-awesome/css/line-awesome.css';
import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import './globals.css';

const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={lato.className}>
        <div className='flex min-h-screen'>
          <Sidebar />
          <main className='flex-1 min-w-0 overflow-auto'>{children}</main>
        </div>
      </body>
    </html>
  );
}
